"""Real-Redis + real-Postgres integration test for F-PERF-4 / SC-004.

Drives a 50-autosave / 10-second burst against the live blog stack and
asserts that both median and p99 flush-lock hold-time drop ≥30% versus
the captured baseline at ``tests/fixtures/flush_lock_hold_baseline.json``.

The baseline is generated by running, against the unmodified codebase
(before the F-PERF-4 reorder lands):

    uv run python scripts/measure_flush_lock_hold.py \\
        --output tests/fixtures/flush_lock_hold_baseline.json

The test calls the same ``measure()`` helper so both runs share the
exact instrumentation seam — a wrapper around
:meth:`AutosaveStore.acquire_flush_lock` that records
``perf_counter`` deltas around the body of the ``async with`` block.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

from apps.core.redis import get_redis_client

_PROJECT_ROOT: Path = Path(__file__).resolve().parents[3]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from scripts.measure_flush_lock_hold import measure  # noqa: E402

_BASELINE_PATH: Path = _PROJECT_ROOT / "tests" / "fixtures" / "flush_lock_hold_baseline.json"
_PAYLOAD_PATH: Path = _PROJECT_ROOT / "scripts" / "synthetic_large_post.json"

# Post-change runs must consume no more than 70% of the baseline (i.e.
# a ≥30% reduction on both central tendency and tail).
_REDUCTION_BUDGET: float = 0.70

pytestmark = [
    pytest.mark.skipif(
        get_redis_client() is None,
        reason="Redis required for flush-lock hold-time measurement.",
    ),
    pytest.mark.skipif(
        not _BASELINE_PATH.exists(),
        reason=(f"Baseline not captured at {_BASELINE_PATH}. Run scripts/measure_flush_lock_hold.py first."),
    ),
    pytest.mark.skipif(
        not _PAYLOAD_PATH.exists(),
        reason=(f"Synthetic payload missing at {_PAYLOAD_PATH}. Run scripts/generate_synthetic_large_post.py first."),
    ),
]


async def test_flush_lock_hold_drops_at_least_30pct_vs_baseline() -> None:
    """The reorder must cut both median and p99 lock-hold by ≥30%."""
    # Test setup is intentionally synchronous file I/O — small fixture
    # reads on session-local disk; not a network or contended resource.
    baseline = json.loads(_BASELINE_PATH.read_text(encoding="utf-8"))  # noqa: ASYNC240
    payload = json.loads(_PAYLOAD_PATH.read_text(encoding="utf-8"))  # noqa: ASYNC240

    result = await measure(samples=50, duration=10.0, payload=payload)

    median_budget_ms = _REDUCTION_BUDGET * baseline["median_ms"]
    p99_budget_ms = _REDUCTION_BUDGET * baseline["p99_ms"]

    # 50 cycles drive 50 acquire calls; tolerate a couple of dropped
    # samples (e.g. a transient SET-NX miss) without making the test
    # flaky. The percentile assertions below are computed off whatever
    # samples did land — and remain statistically meaningful at >=45.
    assert result["count"] >= 45, f"too few lock-hold samples: {result['count']}/50"
    assert result["median_ms"] <= median_budget_ms, (
        f"median lock-hold did not improve by ≥30%: "
        f"post-change {result['median_ms']:.2f}ms vs baseline {baseline['median_ms']:.2f}ms "
        f"(budget ≤ {median_budget_ms:.2f}ms)"
    )
    assert result["p99_ms"] <= p99_budget_ms, (
        f"p99 lock-hold did not improve by ≥30%: "
        f"post-change {result['p99_ms']:.2f}ms vs baseline {baseline['p99_ms']:.2f}ms "
        f"(budget ≤ {p99_budget_ms:.2f}ms)"
    )
