"""add post_versions table

Revision ID: 4206aa588d85
Revises: c2bf7e91d4a0
Create Date: 2026-05-12 15:26:22.056287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import apps.core.database.types

# revision identifiers, used by Alembic.
revision: str = '4206aa588d85'
down_revision: Union[str, Sequence[str], None] = 'c2bf7e91d4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_versions',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_json_compressed', postgresql.BYTEA(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('is_published_snapshot', sa.Boolean(), nullable=False),
    sa.Column('is_restored', sa.Boolean(), nullable=False),
    sa.Column('status_at_save', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', apps.core.database.types.DateTimeUTC(), nullable=False),
    sa.Column('updated_at', apps.core.database.types.DateTimeUTC(), nullable=False),
    sa.CheckConstraint('NOT (is_published_snapshot AND is_restored)', name=op.f('ck_post_versions_ck_post_versions_publish_xor_restore')),
    sa.CheckConstraint('char_length(content_hash) = 64', name=op.f('ck_post_versions_ck_post_versions_content_hash_len')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_post_versions_ck_post_versions_version_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_post_versions_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_versions_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_post_versions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_versions')),
    sa.UniqueConstraint('post_id', 'version', name='uq_post_versions_post_version')
    )
    op.create_index(op.f('ix_post_versions_post_id'), 'post_versions', ['post_id'], unique=False)
    op.create_index('ix_post_versions_post_id_created_at_desc', 'post_versions', ['post_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('ix_post_versions_post_id_published_excl', 'post_versions', ['post_id'], unique=False, postgresql_where='NOT is_published_snapshot')
    op.create_index('ix_post_versions_post_id_version_desc', 'post_versions', ['post_id', 'version'], unique=False, postgresql_ops={'version': 'DESC'})
    op.create_index('ix_post_versions_workspace_published', 'post_versions', ['workspace_id', 'is_published_snapshot'], unique=False, postgresql_where='is_published_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_versions_workspace_published', table_name='post_versions', postgresql_where='is_published_snapshot')
    op.drop_index('ix_post_versions_post_id_version_desc', table_name='post_versions', postgresql_ops={'version': 'DESC'})
    op.drop_index('ix_post_versions_post_id_published_excl', table_name='post_versions', postgresql_where='NOT is_published_snapshot')
    op.drop_index('ix_post_versions_post_id_created_at_desc', table_name='post_versions', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('ix_post_versions_post_id'), table_name='post_versions')
    op.drop_table('post_versions')
    # ### end Alembic commands ###
