"""add product module

Revision ID: a8e6c92843a1
Revises: bd2a57e2dd9d
Create Date: 2026-04-09 20:41:12.016579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import apps.core.database.types

# revision identifiers, used by Alembic.
revision: str = "a8e6c92843a1"
down_revision: Union[str, Sequence[str], None] = "bd2a57e2dd9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_categorys",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.Column("updated_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.Column("deleted_at", apps.core.database.types.DateTimeUTC(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_categorys")),
    )
    op.create_index(
        op.f("ix_product_categorys_display_order"),
        "product_categorys",
        ["display_order"],
        unique=False,
    )
    op.create_index(op.f("ix_product_categorys_slug"), "product_categorys", ["slug"], unique=True)
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=280), nullable=False),
        sa.Column("ingredients", sa.Text(), nullable=True),
        sa.Column("production", sa.Text(), nullable=True),
        sa.Column("benefits", sa.Text(), nullable=True),
        sa.Column("retail_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("wholesale_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.Column("updated_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.Column("deleted_at", apps.core.database.types.DateTimeUTC(), nullable=True),
        sa.CheckConstraint(
            "retail_price >= 0",
            name=op.f("ck_products_ck_products_retail_price_non_negative"),
        ),
        sa.CheckConstraint(
            "wholesale_price IS NULL OR wholesale_price >= 0",
            name=op.f("ck_products_ck_products_wholesale_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categorys.id"],
            name=op.f("fk_products_category_id_product_categorys"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(
        "ix_products_available_category",
        "products",
        ["is_available", "category_id"],
        unique=False,
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_is_available"), "products", ["is_available"], unique=False)
    op.create_index(op.f("ix_products_is_featured"), "products", ["is_featured"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(
        "ix_products_search_vector",
        "products",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)
    op.create_table(
        "product_images",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.Column("updated_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
    )
    op.create_index(
        op.f("ix_product_images_product_id"),
        "product_images",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        "ix_product_images_product_order",
        "product_images",
        ["product_id", "display_order"],
        unique=False,
    )
    # ### end Alembic commands ###

    # PostgreSQL full-text search: auto-maintain products.search_vector via trigger.
    # Uses the 'simple' config so Vietnamese (unaccented) tokens are indexed as-is
    # without an English stemmer mangling them.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION products_search_vector_update() RETURNS trigger AS $$
        BEGIN
          NEW.search_vector :=
            setweight(to_tsvector('simple', COALESCE(NEW.name, '')), 'A') ||
            setweight(to_tsvector('simple', COALESCE(NEW.ingredients, '')), 'B') ||
            setweight(to_tsvector('simple', COALESCE(NEW.benefits, '')), 'B') ||
            setweight(to_tsvector('simple', COALESCE(NEW.production, '')), 'C');
          RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER products_search_vector_trigger
        BEFORE INSERT OR UPDATE OF name, ingredients, benefits, production
        ON products
        FOR EACH ROW EXECUTE FUNCTION products_search_vector_update();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS products_search_vector_trigger ON products;")
    op.execute("DROP FUNCTION IF EXISTS products_search_vector_update();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_images_product_order", table_name="product_images")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_index("ix_products_search_vector", table_name="products", postgresql_using="gin")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_is_featured"), table_name="products")
    op.drop_index(op.f("ix_products_is_available"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index("ix_products_available_category", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_product_categorys_slug"), table_name="product_categorys")
    op.drop_index(op.f("ix_product_categorys_display_order"), table_name="product_categorys")
    op.drop_table("product_categorys")
    # ### end Alembic commands ###
