"""auth_2fa_oauth_otp

Revision ID: b4ca484cf832
Revises: 385c1774f95d
Create Date: 2026-04-07 18:07:01.534032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import apps.core.database.types

# revision identifiers, used by Alembic.
revision: str = "b4ca484cf832"
down_revision: Union[str, Sequence[str], None] = "385c1774f95d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Notes:
        - ``refresh_tokens.token_hash`` / ``expires_at`` are NOT NULL with no
          default. Existing rows (from the auth-stub iteration) cannot
          satisfy this, so we truncate the table first. Refresh tokens are
          ephemeral; truncating only forces clients to log in again.
        - ``users.is_2fa_enabled`` defaults to false at the column level so
          existing user rows can populate the new column.
    """
    op.execute("TRUNCATE TABLE refresh_tokens")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("expires_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.Column("used_at", apps.core.database.types.DateTimeUTC(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.Column("updated_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_email_verifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_verifications")),
    )
    op.create_index(op.f("ix_email_verifications_user_id"), "email_verifications", ["user_id"], unique=False)
    op.create_index(
        "ix_email_verifications_user_id_purpose_used_at",
        "email_verifications",
        ["user_id", "purpose", "used_at"],
        unique=False,
    )
    op.add_column("refresh_tokens", sa.Column("token_hash", sa.String(length=64), nullable=False))
    op.add_column("refresh_tokens", sa.Column("expires_at", apps.core.database.types.DateTimeUTC(), nullable=False))
    op.add_column("refresh_tokens", sa.Column("revoked_at", apps.core.database.types.DateTimeUTC(), nullable=True))
    op.add_column("refresh_tokens", sa.Column("replaced_by_id", sa.UUID(), nullable=True))
    op.add_column("refresh_tokens", sa.Column("user_agent", sa.String(length=255), nullable=True))
    op.add_column("refresh_tokens", sa.Column("ip_address", sa.String(length=45), nullable=True))
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_index("ix_refresh_tokens_user_id_revoked_at", "refresh_tokens", ["user_id", "revoked_at"], unique=False)
    op.drop_constraint(op.f("fk_refresh_tokens_user_id_users"), "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
        "refresh_tokens",
        "refresh_tokens",
        ["replaced_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_refresh_tokens_user_id_users"), "refresh_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("email_verified_at", apps.core.database.types.DateTimeUTC(), nullable=True))
    op.add_column("users", sa.Column("google_sub", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("totp_secret", sa.String(length=64), nullable=True))
    op.add_column(
        "users",
        sa.Column("is_2fa_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(op.f("ix_users_google_sub"), "users", ["google_sub"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_sub"), table_name="users")
    op.drop_column("users", "is_2fa_enabled")
    op.drop_column("users", "totp_secret")
    op.drop_column("users", "google_sub")
    op.drop_column("users", "email_verified_at")
    op.drop_constraint(op.f("fk_refresh_tokens_user_id_users"), "refresh_tokens", type_="foreignkey")
    op.drop_constraint(op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"), "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(op.f("fk_refresh_tokens_user_id_users"), "refresh_tokens", "users", ["user_id"], ["id"])
    op.drop_index("ix_refresh_tokens_user_id_revoked_at", table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "ip_address")
    op.drop_column("refresh_tokens", "user_agent")
    op.drop_column("refresh_tokens", "replaced_by_id")
    op.drop_column("refresh_tokens", "revoked_at")
    op.drop_column("refresh_tokens", "expires_at")
    op.drop_column("refresh_tokens", "token_hash")
    op.drop_index("ix_email_verifications_user_id_purpose_used_at", table_name="email_verifications")
    op.drop_index(op.f("ix_email_verifications_user_id"), table_name="email_verifications")
    op.drop_table("email_verifications")
    # ### end Alembic commands ###
