"""add object_permissions table

Revision ID: bd2a57e2dd9d
Revises: cfac2e0b4659
Create Date: 2026-04-07 22:11:09.137877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import apps.core.database.types

# revision identifiers, used by Alembic.
revision: str = "bd2a57e2dd9d"
down_revision: Union[str, Sequence[str], None] = "cfac2e0b4659"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_permissions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resource", sa.String(length=100), nullable=False),
        sa.Column("object_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.Column("updated_at", apps.core.database.types.DateTimeUTC(), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_object_permissions_granted_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_object_permissions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_permissions")),
        sa.UniqueConstraint("user_id", "resource", "object_id", "action", name="uq_rbac_object_permissions"),
    )
    op.create_index("idx_rbac_object_permissions_expires", "object_permissions", ["expires_at"], unique=False)
    op.create_index(
        "idx_rbac_object_permissions_resource_object", "object_permissions", ["resource", "object_id"], unique=False
    )
    op.create_index(
        "idx_rbac_object_permissions_user_resource_object",
        "object_permissions",
        ["user_id", "resource", "object_id"],
        unique=False,
    )
    op.create_unique_constraint(op.f("uq_groups_name"), "groups", ["name"])
    op.create_unique_constraint(op.f("uq_permissions_name"), "permissions", ["name"])
    op.create_unique_constraint(op.f("uq_roles_name"), "roles", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_roles_name"), "roles", type_="unique")
    op.drop_constraint(op.f("uq_permissions_name"), "permissions", type_="unique")
    op.drop_constraint(op.f("uq_groups_name"), "groups", type_="unique")
    op.drop_index("idx_rbac_object_permissions_user_resource_object", table_name="object_permissions")
    op.drop_index("idx_rbac_object_permissions_resource_object", table_name="object_permissions")
    op.drop_index("idx_rbac_object_permissions_expires", table_name="object_permissions")
    op.drop_table("object_permissions")
    # ### end Alembic commands ###
