"""add rbac tables

Revision ID: cfac2e0b4659
Revises: b4ca484cf832
Create Date: 2026-04-07 21:59:08.176795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import apps.core.database.types

# revision identifiers, used by Alembic.
revision: str = 'cfac2e0b4659'
down_revision: Union[str, Sequence[str], None] = 'b4ca484cf832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('display_name', sa.String(length=200), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('is_system', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('parent_id', sa.BigInteger(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.Column('updated_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['groups.id'], name=op.f('fk_groups_parent_id_groups'), ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
                    sa.UniqueConstraint('name', name='uq_rbac_groups_name'),
                    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
                    )
    op.create_index('idx_rbac_groups_active_level', 'groups', ['is_active', 'level'], unique=False)
    op.create_index('idx_rbac_groups_parent_active', 'groups', ['parent_id', 'is_active'], unique=False)
    op.create_index('idx_rbac_groups_system_active', 'groups', ['is_system', 'is_active'], unique=False)
    op.create_table('permissions',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('display_name', sa.String(length=200), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('resource', sa.String(length=100), nullable=False),
                    sa.Column('action', sa.String(length=50), nullable=False),
                    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('is_system', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('category', sa.String(length=50), nullable=True),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.Column('updated_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.Column('deleted_at', apps.core.database.types.DateTimeUTC(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
                    sa.UniqueConstraint('name', name='uq_rbac_permissions_name'),
                    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
                    )
    op.create_index('idx_rbac_permissions_active', 'permissions', ['is_active'], unique=False)
    op.create_index('idx_rbac_permissions_category_active', 'permissions', ['category', 'is_active'], unique=False)
    op.create_index('idx_rbac_permissions_deleted', 'permissions', ['deleted_at'], unique=False)
    op.create_index('idx_rbac_permissions_resource_action', 'permissions', ['resource', 'action'], unique=False)
    op.create_table('roles',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('display_name', sa.String(length=200), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('is_system', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('parent_id', sa.BigInteger(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.Column('updated_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['roles.id'], name=op.f('fk_roles_parent_id_roles'), ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
                    sa.UniqueConstraint('name', name='uq_rbac_roles_name'),
                    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
                    )
    op.create_index('idx_rbac_roles_active_level', 'roles', ['is_active', 'level'], unique=False)
    op.create_index('idx_rbac_roles_parent_active', 'roles', ['parent_id', 'is_active'], unique=False)
    op.create_index('idx_rbac_roles_system_active', 'roles', ['is_system', 'is_active'], unique=False)
    op.create_table('group_roles',
                    sa.Column('group_id', sa.BigInteger(), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('assigned_by', sa.UUID(), nullable=True),
                    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.Column('updated_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_group_roles_assigned_by_users'), ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_roles_group_id_groups'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_group_roles_role_id_roles'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_roles')),
                    sa.UniqueConstraint('group_id', 'role_id', name='uq_rbac_group_roles')
                    )
    op.create_index('idx_rbac_group_roles_active_expires', 'group_roles', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_rbac_group_roles_expires', 'group_roles', ['expires_at'], unique=False)
    op.create_index('idx_rbac_group_roles_group_active', 'group_roles', ['group_id', 'is_active'], unique=False)
    op.create_index('idx_rbac_group_roles_role', 'group_roles', ['role_id'], unique=False)
    op.create_table('role_permissions',
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('permission_id', sa.BigInteger(), nullable=False),
                    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('granted_by', sa.UUID(), nullable=True),
                    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.Column('updated_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_role_permissions_granted_by_users'), ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
                    sa.UniqueConstraint('role_id', 'permission_id', name='uq_rbac_role_permissions')
                    )
    op.create_index('idx_rbac_role_permissions_active_expires', 'role_permissions', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_rbac_role_permissions_expires', 'role_permissions', ['expires_at'], unique=False)
    op.create_index('idx_rbac_role_permissions_permission', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_rbac_role_permissions_role_active', 'role_permissions', ['role_id', 'is_active'], unique=False)
    op.create_table('user_groups',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('group_id', sa.BigInteger(), nullable=False),
                    sa.Column('assigned_by', sa.UUID(), nullable=True),
                    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('role', sa.String(length=50), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.Column('updated_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_groups_assigned_by_users'), ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_group_id_groups'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_user_id_users'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_groups')),
                    sa.UniqueConstraint('user_id', 'group_id', name='uq_rbac_user_groups')
                    )
    op.create_index('idx_rbac_user_groups_active_expires', 'user_groups', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_rbac_user_groups_expires', 'user_groups', ['expires_at'], unique=False)
    op.create_index('idx_rbac_user_groups_group', 'user_groups', ['group_id'], unique=False)
    op.create_index('idx_rbac_user_groups_user_active', 'user_groups', ['user_id', 'is_active'], unique=False)
    op.create_table('user_roles',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('assigned_by', sa.UUID(), nullable=True),
                    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.Column('updated_at', apps.core.database.types.DateTimeUTC(), nullable=False),
                    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_roles_assigned_by_users'), ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
                    sa.UniqueConstraint('user_id', 'role_id', name='uq_rbac_user_roles')
                    )
    op.create_index('idx_rbac_user_roles_active_expires', 'user_roles', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_rbac_user_roles_expires', 'user_roles', ['expires_at'], unique=False)
    op.create_index('idx_rbac_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_rbac_user_roles_user_active', 'user_roles', ['user_id', 'is_active'], unique=False)
    op.alter_column('casbin_rule', 'ptype',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casbin_rule', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('casbin_rule', 'ptype',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('idx_rbac_user_roles_user_active', table_name='user_roles')
    op.drop_index('idx_rbac_user_roles_role', table_name='user_roles')
    op.drop_index('idx_rbac_user_roles_expires', table_name='user_roles')
    op.drop_index('idx_rbac_user_roles_active_expires', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_rbac_user_groups_user_active', table_name='user_groups')
    op.drop_index('idx_rbac_user_groups_group', table_name='user_groups')
    op.drop_index('idx_rbac_user_groups_expires', table_name='user_groups')
    op.drop_index('idx_rbac_user_groups_active_expires', table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_index('idx_rbac_role_permissions_role_active', table_name='role_permissions')
    op.drop_index('idx_rbac_role_permissions_permission', table_name='role_permissions')
    op.drop_index('idx_rbac_role_permissions_expires', table_name='role_permissions')
    op.drop_index('idx_rbac_role_permissions_active_expires', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('idx_rbac_group_roles_role', table_name='group_roles')
    op.drop_index('idx_rbac_group_roles_group_active', table_name='group_roles')
    op.drop_index('idx_rbac_group_roles_expires', table_name='group_roles')
    op.drop_index('idx_rbac_group_roles_active_expires', table_name='group_roles')
    op.drop_table('group_roles')
    op.drop_index('idx_rbac_roles_system_active', table_name='roles')
    op.drop_index('idx_rbac_roles_parent_active', table_name='roles')
    op.drop_index('idx_rbac_roles_active_level', table_name='roles')
    op.drop_table('roles')
    op.drop_index('idx_rbac_permissions_resource_action', table_name='permissions')
    op.drop_index('idx_rbac_permissions_deleted', table_name='permissions')
    op.drop_index('idx_rbac_permissions_category_active', table_name='permissions')
    op.drop_index('idx_rbac_permissions_active', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('idx_rbac_groups_system_active', table_name='groups')
    op.drop_index('idx_rbac_groups_parent_active', table_name='groups')
    op.drop_index('idx_rbac_groups_active_level', table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
